-- AlterTable
ALTER TABLE "TenantConfig" ADD COLUMN IF NOT EXISTS "moduleClasses" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TenantConfig" ADD COLUMN IF NOT EXISTS "moduleInscriptions" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TenantConfig" ADD COLUMN IF NOT EXISTS "modulePersonnel" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TenantConfig" ADD COLUMN IF NOT EXISTS "moduleRapports" BOOLEAN NOT NULL DEFAULT true;
